services:
  feed:
    build:
      context: .
      dockerfile: ./apps/feed/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    env_file:
      - .env

  posts:
    build:
      context: .
      dockerfile: ./apps/posts/Dockerfile
    ports:
      - "3002:3002"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    env_file:
      - .env

  users:
    build:
      context: .
      dockerfile: ./apps/users/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - NODE_ENV=production
    env_file:
      - .env